### ISSUE TITLE
Config File Error

### ISSUE THREAD

**Issue by adamljohns** [decred/decrediton#1006]
I'm getting the following error on my Mac, which is OS High Sierra... now that I think about it, updating to the new OS might have been the start of this problem...  Any advice would be appreciated.  I'd really like to get back into the Decredition app!

Config File Error
There was an error while trying to load the config file, the format is invalid.

File: /Users/adamjohns/Library/Application Support/decrediton/config.json
Error: SyntaxError: Unexpected end of JSON input

**Comment by alexlyp** [comment]
Try to delete the config.json and open decrediton again.

**Comment by adamljohns** [comment]
unfortunately when I search for that file, nothing shows up... Like I said earlier, I think it might be a result of upgrading my iOS, but unfortunately I don't have a time machine back-up, I'm stuck where I'm at...  Any ideas on how to find this "config.json" file? or what to do if it doesn't exist

**Comment by matheusd** [comment]
Please look at the table at the end of this page for the location of config.json:

https://docs.decred.org/getting-started/user-guides/decrediton-setup/#troubleshooting

**Comment by matheusd** [comment]
If it doesn't exist, it should be created automatically once Decrediton runs.

**Comment by adamljohns** [comment]
Ok, I don’t see it, I’m not sure if it got deleted somehow... I’ve run Decredation on this computer before, so I don’t know why it’s not there... can I install Decredation on another computer and then copy those files over once they show up?

**Comment by matheusd** [comment]
You could but there shouldn't be any need to. If you're only missing the `config.json` file, it should be created once you run decrediton. If you are missing other files, then you should uninstall decrediton, then install it again

**Make sure you have your seed written down in a safe place** before doing anything, as losing access to your seed and wallet.db file means you lose your money.

You can also try to install decrediton on another computer and import the seed there to make sure everything is ok, but only do that **if you trust the computer**, otherwise your seed can be stolen and your funds lost.

**Comment by adamljohns** [comment]
ok, phew, that did it.  I had to right click on one of the folders and click "show library". man, how did that folder get hidden!?  ha!  Well, thanks for the help!  You helped me get my 79 DCR back!
