### ISSUE TITLE
Error opening program - Decrediton had to close due to an error

### ISSUE THREAD

**Issue by kemtrale** [decred/decrediton#1012]
![image](https://user-images.githubusercontent.com/34675212/34147284-43509a26-e4f1-11e7-82e6-6d5e64062d08.png)
I am receiving this error every time I attempt to log into the wallet - since the update I have been unable to open anything, and beforehand would get a .json error.

**Comment by matheusd** [comment]
Please close Decrediton, then check the task manager of your OS for any processes called `dcrd` or `dcrwallet`. If any of them are running, shut them down, then try to restart.

If that doesn't work, please check the log files if there are any error messages. You can see the logs in the main menu (Advanced -> Show Wallet Log files/Show Daemon Log Files) or on your install dir (see this page: https://docs.decred.org/getting-started/user-guides/decrediton-setup/#troubleshooting).

**Comment by kemtrale** [comment]
![image](https://user-images.githubusercontent.com/34675212/34210053-964d1efa-e5e8-11e7-91a2-78ebf5ee3935.png)
<img width="644" alt="screen shot 2017-12-21 at 12 46 22 am" src="https://user-images.githubusercontent.com/34675212/34210058-9b8bc5b0-e5e8-11e7-94a5-154ad74aea7d.png">

**Comment by kemtrale** [comment]
@matheusd 
Thankyou.
I tried the activity monitor process before posting; does the above image help at all?

**Comment by alexlyp** [comment]
So oddly enough this looks like you are running a very old version of dcrwallet.  What version of decrediton are you using?

**Comment by kemtrale** [comment]
Running v1.1.2 - most recent download link on the decrediton site has this
as the mac download.

**Comment by jiecut42** [comment]
One thing with my windows decredition was that it would hang and stall while it was drawing that animation. So I had to exit the program, and then restart it. Eventually, I was able to get lucky and the wallet was able to load without the animation stalling.

**Comment by matheusd** [comment]
@kemtrale notice on your second screenshot, 4th line says "1.0.1+release". It should have been "1.1.2+release".

This means you probably have an older version still installed somewhere that is being started instead of the correct version. I'd advise you do the following:

- **Make sure you have your seeds**
- Copy your `wallet.db` file somewhere as a temporary backup. Remember to remove it afterwards.
- Uninstall decrediton
- Look for older installs of decrediton, `dcrd`, `dcrwallet` or `dcrinstall`. One possible way: open a command line prompt, type `which dcrwallet` and see if anything comes up. Remove any older versions you find.
- Reinstall decrediton
- See on the logs if the correct version comes up.

@jiecut42 in which stage (look at the top header) did it hang? Always on the same one? Could you check the logs once it hangs to see if there's any error message?

**Comment by jiecut42** [comment]
I think it's usually the first stage. I don't see wallet logs (just shutdown from last session). drcd logs don't have errors.

I get this javascript popup error though.

https://i.imgur.com/cPJZv7d.png

@matheusd

**Comment by matheusd** [comment]
@jiecut42  Right, this one is a known issue on windows platforms (#995). We should have a bugfix release for that online later today or tomorrow.

**Comment by kemtrale** [comment]
Still nothing after a deletion and a reinstall. Dont believe there is a
'which' command for terminal either, but a search of hidden files showed no
remaining files from previous install before reinstalling.
I'll just have to use my windows I suppose, but it's a bit of an
inconvenience.

**Comment by matheusd** [comment]
After reinstalling, what do the logs show for the version (`DCRW: version X.Y.Z+release`)?

**Comment by maxr0s3** [comment]
same issue
