### ISSUE TITLE
Discrepancy with missed tickets

### ISSUE THREAD

**Issue by EchterAgo** [decred/decrediton#1022]
Under Tickets | Purchase Tickets, I see this:

![image](https://user-images.githubusercontent.com/922233/34246978-62f5f678-e663-11e7-853f-73c55baea4bb.png)

Note that missed tickets counter is 0. However, under Tickets | My Tickets, I see this:

![image](https://user-images.githubusercontent.com/922233/34247031-a6e35ede-e663-11e7-98e6-3861fa6a713f.png)

There are 2 missed tickets. In the details it shows this:

![image](https://user-images.githubusercontent.com/922233/34247101-ee7f2016-e663-11e7-8d8e-ae52acf37188.png)

One of the those ticket TX is this:

https://mainnet.decred.org/tx/84580c14e26e20e414a61f75fdab3681ac0d8818afdc48bbb9d14a6cebecdd87

But I'm not sure how to check if this ticket was actually missed. My staking pool says there were no missed tickets:

![image](https://user-images.githubusercontent.com/922233/34247152-1417f8b6-e664-11e7-8f44-2aed662e42c7.png)

Where is that difference coming from? Do I need to do anything about this?

**Comment by matheusd** [comment]
We're tracking some inconsistencies between the stake info screen and the my tickets page. A new version should be released (probably today) with some fixes. 

The ticket you linked appears to have been voted yesterday. Notice the address on the second sstxcommitment output is the return to your wallet (first one is to the stakepool). Here's the vote tx:

https://explorer.dcrdata.org/explorer/tx/86336554e9df3cfef572cb41d697abbac565e98361cae671336970df115af7de

Notice the second stakegen output being sent to the address of the second sstxcommitment. 

The vote was issued yesterday (dec 20, 14:33 UTC). Did you leave your wallet online since then? If so, this is a known problem (which should be fixed on the bugfix release). Try reloading the UI (menu view -> reload UI) or close and restart Decrediton.

**Comment by EchterAgo** [comment]
No, I didn't run the client the whole time. Reloading the UI did indeed fix the display issue. Thanks!
