### ISSUE TITLE
Upgrading to node v9.11.1 causes an uncaught error 

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#1328]
Cannot find module 'config'

I'll try and look around for existing issues in github.com/electron/electron to see if it's a known issue elsewhere.

**Comment by matheusd** [comment]
I haven't been able to find the root cause for this, but the gist of the problem is that webpack on node > 8.5.0 generates an external module called "config" and that messes up the module loading.

You can verify that by switching to node 9 or 10, then do a `yarn dev', go to the developer tools, "sources" tab, expand the `webpack://` entry and you should see an "external config" entry.

The solution that works is changing all imports of the config file to use `import ... from ./config` instead of just `from config`. 

I still don't know what update in node caused it, but I'll send the PR fix in a bit.
