### ISSUE TITLE
White screen opening wallet

### ISSUE THREAD

**Issue by pedropilla** [decred/decrediton#1387]
Last week was working, using 1.1.3. Yesterday I get this bug, dont know why, so downloaded 1.2.1 and same situation, I'm running fedora 27, the daemon works OK apparently (logs OK) but when I open wallet get the white screen and no logs are generated.

I'm running with '--ignore-gpu-blacklist', when I try to open Dev Tools get a popup with 'Devtools was disconnected from page. Once page is reloaded, devtools will automatically reconnect'

**Comment by matheusd** [comment]
Are you running inside a VM or using some other restriction when running it?

When that happens, try pressing F5 or click on the View -> Reload UI menu and see if it shows up.

**Comment by pedropilla** [comment]
No, running directly, SElinux was active but now disabled and same situation.

Nothing happens when I try "Reload UI" or F5.

**Comment by pedropilla** [comment]
Enabled SElinux to see the error, I was getting a deny from SElinux in PHP-FPM, so I disabled httpd and php-fpm, disabled SElinux and rebooted but same situation. No logs generated in .config/decrediton/logs/mainnet

**Comment by matheusd** [comment]
@pedropilla 

While I get the white screen bug, reloading the UI consistently solves it and since this started happening in 1.1.3 I'm thinking it's something on the OS that's blocking the app.

We've recently upgraded the electron/chrome version on current master and I've added a few log lines at startup to try and zero in on where exactly of the startup procedure the app stops loading. I don't seem to get the white screen problem on this latest master.

If you're willing to try running the bleeding edge version to see if it solves the issue, I can generate binaries for you or you can build the latest version yourself if you have the knowledge.

You can also find me on slack if you want a faster turnout time.

**Comment by pedropilla** [comment]
Ok, I will try to build latest and find you on slack, thanks in advance!

Em Seg, 14 de mai de 2018 11:59, Matheus Degiovani <notifications@github.com>
escreveu:

**Comment by icole** [comment]
@pedropilla Did running the latest version solve this for you? I am encountering the same issue on Fedora 28

**Comment by matheusd** [comment]
FYI, just tested the rpm version on a brand new fedora 28 install and I'm able to reproduce the issue.

The specific error I'm getting on the logs is a failed security handshake. 

I'll do some more tests today and update the issue.

**Comment by matheusd** [comment]
Still running some tests, but I'm pretty convinced the underlying issue is this one: #1485 

Seems that the older grpc libs aren't compatible to fedora 28 (and a bunch of other systems). If that's so, then the only solution is to wait for a new release.
