### ISSUE TITLE
Visual/Motion Design: Updates to onboarding slides

### ISSUE THREAD

**Issue by linnutee** [decred/decrediton#1483]
Preview: https://xd.adobe.com/view/e93def3b-fb95-4b67-42b2-963ccd7db58c-9f0c/
Specs: https://xd.adobe.com/spec/200f3ec0-0db7-461e-5135-2622568d0565-563e/
Animation mp4's: https://drive.google.com/drive/folders/18lHNfTnKJbSfBVzKx0X127fU_103JKpb?usp=sharing 

This update contains the motion design work for the onboarding slides we've done with @kyleFirethought. New update includes 4 slides with animation loops illustrating each slides key topics. 

- Each animation should be playing in a endless loop. No controls are displayed.
- The UI layout has been slightly adjusted, area for animations is now larger in width. 
- Preview includes an updated copy. This is largely based on the copywriting contributions done for Decred booklet. If anyone wishes to contribute in refining it for a smoother and more concentrated reading experience – post here or #1402 and discuss with #writers_room on slack. 
- Typographic concerns: the text styles are with Source Sans Pro Regular and Semi-Bold (not normal Bold). Lighter text in brackets is with color #959DAC. Bulletpoints in slide 3 should be styled accordingly outside the paragraph div. 

<img width="766" alt="screen shot 2018-06-20 at 16 49 21" src="https://user-images.githubusercontent.com/17774057/41662499-f8677e46-74a9-11e8-946f-60d881b0c454.png">

**Comment by heyvj** [comment]
Here is the updated text for each of the 4 sections. My aims when writing this were:

- Get the reader excited about Decred so open each section with benefits or warnings rather than features
- Improve the reader’s understanding of Decred so they are better able to talk about Decred accurately to other people
- Be concise and engage the reader so that each section is actually read, not skipped blindly

Note: If we knew more about the users of Decrediton we could refine the level of technicality in this copy – perhaps something for a future iteration. 

I have also attached a longer file outlining my approach and rationale behind this copy, and text for an optional Section 5 we may want to include for further reading. [Wallet Copy & Analysis.pdf](https://github.com/decred/decrediton/files/2134467/Wallet.Copy.Analysis.pdf)

------


**Section 1**
Blockchains are fundamental to cryptocurrencies. At the heart of Decred is a particularly unique blockchain – a hybrid blockchain that is mined by both proof-of-work (PoW) and proof-of-stake (PoS) miners.

Like many cryptocurrencies, Decred's blockchain keeps the network safe and serves as a global decentralized ledger by validating and recording transactions.

All Decred transactions are recorded on the blockchain and it keeps track of how much Decred is sent by and to whom and the balance of Decred in every account.

Unlike most cryptocurrencies, Decred's blockchain also facilitates decision making on its own rules (consensus voting) which Decred holders can influence by voting – more on that soon.  

**Section 2**
Understanding how your Decrediton wallet works means you will be able to get the most out of Decred and its unique features.

A wallet is a tool that interacts with the blockchain to send and receive Decred funds. Your wallet is also keeping track of your Decred balance and acting as a personal ledger of your transactions. 

In addition to the above, your Decrediton wallet can also be used to take part in proof-of-stake (PoS) mining, allowing you to vote on the future of Decred - for example, the features that get built and the community projects that get funded. The next section goes into this in more detail. 

It is important to understand that your wallet is generated based on a mnemonic referred to as the seed. Your seed is a list of 33 words that can restore your wallet if you lose your password (for example, if you forget your encryption passphrase or if your computer, your wallet hardware, breaks). The seed is necessary and sufficient to re-create your wallet. The same seed can also be used to backup your wallet and export it to other Decred clients. 

**Section 3**
Anyone with enough Decred funds in their wallet can become a proof-of-stake (PoS) voter and earn voting rewards in the form of more Decred. 

To do this, you need to have enough Decred funds in your wallet to buy at least one “ticket” and lock these funds for a random duration of time, approximately between 1 and 142 days. By doing this and participating in community governance, you are rewarded with more Decred. 

As a PoS voter, you vote on the validity of blocks mined by proof of work miners – the validating of blocks is essentially done automatically by Decrediton wallet.

These tickets also carry the right to take part in Decred’s governance by voting on issues which determine the future of Decred – search for “Decred Politeia” to learn more.

Once you have purchased your ticket and it is live, it enters a pool of other tickets called the ticket pool. Tickets from the pool are chosen at random to vote with each block mined. The process is like a lottery at the end of which your ticket cost is returned to you, in most cases with an additional reward for your participation as a PoS voter. 

**Section 4**
Before we finish your on-boarding, you need to understand how to keep your Decred funds secure. Only you are responsible for your security. Remember, if your wallet has been compromised transactions can not be reversed, canceled or refunded. 

To reduce this risk, make a backup of your seed key and password and always keep them safe. 
Do not store them on your computer, in a cloud storage service or in a password manager. If any of these are compromised, the security of your funds is at risk. 

We suggest storing a backup of your seed key and password written down (be sure to test you have written it correctly), print it on a piece of paper for safe keeping or save it to an external drive like a USB stick. 

Do not tell anyone your password or seed key unless you trust them with your Decred funds and be extremely cautious entering them anywhere (particularly, stay safe from “phishing” websites). 
If you lose your seed key and your password, nobody else can recover it and your funds will be lost forever.

**Comment by linnutee** [comment]
Following up to the slack feedback to keep track of this. Please work forward with this iteration as mentioned:  https://xd.adobe.com/view/1a21809a-d432-4470-6263-bd86c83c676c-6c10/ here I’ve ironed out the current copy further to address my previous comments in high level.  

- Consistency in use of terms
- Straight-forward and concise
- Cut out needless weight, bloat and repetitions
- Consistency in writing style and adding conversational tone 

Mainly if this can be fine tuned into a more cohesive style + applied to a more conversational tone, should be good to go. 

Word count per slide:
90 - 150 - 150 - 110 or less

**Comment by matheusd** [comment]
Just to confirm: Can I use the copy on the last slides posted by @linnutee? Or is there any further work being done on the copy?

**Comment by heyvj** [comment]
Hey @matheusd there is another round of iterations to come. @linnutee had some feedback on the last ones. I'm working on them this evening and will discuss with him and fire over as soon as we have reached agreement on the final wording.

**Comment by Jujhar** [comment]
Any update on the wording? Thinking of doing this issue.

**Comment by matheusd** [comment]
Hey jujhar. This is already being solved on PR #1486.
