### ISSUE TITLE
[watch-only]  Various functionalities to hide while isWatchingOnly mode

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#1490]
List of functionality to hide:
- Send DCR
- Tickets (since you can't import scripts/add stakepool)
- Add Accounts
- Change Private Passphrase
- Sign/Verify message

**Comment by vctt94** [comment]
Can I get this one?

**Comment by alexlyp** [comment]
You can start by hiding sign/verify, add accounts and change passphrase.  We need to get some guidance from @linnutee about what to do with the tabs that need to be hidden (send and tickets etc)

**Comment by linnutee** [comment]
Prototype: https://xd.adobe.com/view/f62cab0f-de1d-4385-665c-cdea96b80679-801d/
Specs: https://xd.adobe.com/spec/563119f3-5bbf-43bd-5c65-6b002287f541-2000/
Icons: [decrediton - icons 200718.zip](https://github.com/decred/decrediton/files/2215093/decrediton.-.icons.200718.zip)


Included a design example to address this with disabled states and masking rather than completely hiding. This way neither neither the layout breaks and there's a bit more information available for the user. 
- Full views that have no available functionality (send and tickets) have the content area masked and display a modal (without close option) explaining why the view is disabled. 
- Views that have partial functionality (accounts, settings and security center) either the fields or buttons (or both) in inactive state. 
- When clicking on those states, should trigger a notification with the copy "This functionality is disabled for watch-only Wallets". I didn't do a mock-up for the notification, can just use the current snackbar how it is. It's a further item in the pipeline to do an overhaul for the notifications. 
- Disabled buttons already got an existing style element. Inactive fields on the other hand I think have been mixed up in the past with filled/completed fields to some degree in some instances. Reference from https://github.com/decred/decrediton/issues/1504 and component sheet: https://xd.adobe.com/spec/1c4345df-59aa-4dca-595d-0f82e91ecbaa-6a72/screen/dd46576b-2b5b-4ad3-acc8-80873d6f8b92/UI-component-states/
- Included a disabled icon for the password button and also updated (color) icon for the info modal (should be applied through-out).

**Comment by matheusd** [comment]
Small note: message verification works for watch only wallets, so don't disable that (you can verify messages from any address, not necessarily from your wallet).
