### ISSUE TITLE
[non-advanced] Improve daemon error message

### ISSUE THREAD

**Issue by vctt94** [decred/decrediton#1543]
Right now, the error message when the binaries on the bin folder are outdated is the following: 
![shouldimprove](https://user-images.githubusercontent.com/15069783/42963736-7f245eea-8b6b-11e8-88b1-cc196298085e.png)
 
We should improve this error message noticing that updating the binaries at bin folder would fix the problem and I think we should remove the message which says it needs to delete the blockchain, because it will not fix the problem.

**Comment by Jujhar** [comment]
Should I keep the second part but add "additionally if that does not work you can try" or is it for sure not going to fix this problem when corrupted error or checksum error occurs?

Like so:
_This error means your blockchain data has somehow become corrupted.  Typically, this is caused by a sector on the HDD/SDD that went bad and its built-in SMART didn't repair it, or the more likely case, there was a memory issue which corrupted the data.  <b>To resolve please update or replace the binaries in the bin folder, additionally if that does not work you can try to</b> delete your blockchain data and re-download.  Press the button below to complete the process. When you restart Decrediton, it will automatically begin your blockchain download. Please come to our support channel on slack/matrix/discord/rocketchat to get advice about running disk utilities._

In the second alternative case with deleting mention of blockchain redownload:
_This error means your blockchain data has somehow become corrupted.  Typically, this is caused by a sector on the HDD/SDD that went bad and its built-in SMART didn't repair it, or the more likely case, there was a memory issue which corrupted the data.  <b>To resolve please update or replace the binaries in the bin folder. Please come to our support channel on slack/matrix/discord/rocketchat to get advice about running disk utilities.</b>_

If I were to keep the delete blockchain part then also change the button to a grey instead of red and have it display 'Delete Blockchain Data and Shutdown". Also we can add another button to download and replace binaries if that is possible with permissions, keeping the latest binaries on the server.

**Comment by alexlyp** [comment]
Well actually that error message isn't really applicable to that message, so a new message should be displayed when that message about the incompatible daemon software.  Nothing is actually wrong with the chain in this case.  Just using bad software.

@vctt94 you got this by trying to use an older dcrd (ver 3) after you had already upgraded the db that was from a newer one (ver 4)?

If that's the case then I we should just advise user's to upgrade back to the ver 4 software.

**Comment by vctt94** [comment]
Yeah, that's right @alexlyp. But I believe it is reproducible by using `git checkout` for an older git tag at `dcrd`, and copy it to the bin folder. 

I believe just advising the user to upgrade its bin is fine.

**Comment by alexlyp** [comment]
Right in this case it should be alerted that they are trying to use an older version of dcrd that is no longer compatible with their db. I'd rather not even mention being able to downgrade with a blockchain deletion and restart.  Any dev that wants to do this can figure it out from us, otherwise the general user should be told how to do it imo.
