### ISSUE TITLE
need a more reliable method of finding the block height

### ISSUE THREAD

**Issue by jolan** [decred/decrediton#165]
Code as it stands now can get stuck for awhile fetching 0 headers until a block comes in.

15:14:22 2017-01-13 [INF] WLLT: Fetching headers
15:14:22 2017-01-13 [INF] WLLT: Fetched 0 new header(s)
15:14:23 2017-01-13 [INF] WLLT: Fetching headers
15:14:23 2017-01-13 [INF] WLLT: Fetched 0 new header(s)
15:14:24 2017-01-13 [INF] WLLT: Fetching headers
15:14:24 2017-01-13 [INF] WLLT: Fetched 0 new header(s)

**Comment by jcvernaleo** [comment]
I've hit it a few times too but haven't been able to tell why.

**Comment by alexlyp** [comment]
Currently we use the getAccounts grpc that has the current block height, but obviously not ideal since I'd have to spin up another walletservice instead of everything in the walletloaderservice.  Ideally I'd love for the fetchHeaders response to return the current "best header" as well.  That should solve most of our problems.
