### ISSUE TITLE
language setting options shift to welcome page & chinese version issues

### ISSUE THREAD

**Issue by Guang168** [decred/decrediton#1725]
1. Shift the language settings to the welcome page instead of in the wallet settings. maybe at the corner next to ‘about decrediton’ with a flag or something. 

After Chinese language is selected, below issues. 
~2. Creating a new wallet, on the confirming seed page, there are 2 question marks with pop up for "seed information" and "private passphrase information", are in english~
~3. "learn the basics" and "whats new on 1.3.1" on top left of welcome page is still in english~
~4.  "If you are syncing the blockchain for the first time, this may take a while." are in english~
~5. when i click delete any wallet the same notice saying "delete default-wallet (mainnet)" pops up. it should be delete "name of wallet" for the selected wallet.~

**Comment by Jujhar** [comment]
I can handle this one.

**Comment by alexlyp** [comment]
just fix number 5, @Jujhar

**Comment by Jujhar** [comment]
Done, number 5 fix PR created.

**Comment by alexlyp** [comment]
I've updated this issue to reflect what I've found during my testing.  

I am open to adding a different location for language select since it is a little rough for UX as new languages are added.  @linnutee do you have any thoughts about this?  Should we put a language select that is more easily accessible as new languages are added?

**Comment by matheusd** [comment]
Language selection is now shown during the first decrediton run, so users don't have to search for this anymore. Please reopen if still applicable.
