### ISSUE TITLE
Proposal - User Vote Status needed

### ISSUE THREAD

**Issue by flintknap** [decred/decrediton#1752]
In the Governance --> Under Vote tab.  Next to the proposal names add a symbol that clarifies which proposals the user has or has not voted on.  This will eliminate a lot of clicking in and out of proposals.  

Other GUI options might include color coding Yes votes with green, No votes with red and leaving all other votes the standard blue color.

**Comment by matheusd** [comment]
The tricky bit I see with this is that currently the only way of knowing whether you voted is by requesting the list of tickets eligible for voting in the proposal (from the Politeia site), then requesting the list of cast votes and double checking whether you have eligible tickets that have/have not voted. This would have to be done for _all_ proposals being voted on, every time the wallet is opened.

While we_could_ save this information locally, so far we've been pretty reticent in saving anything locally outside of the wallet, due to being yet another data store that we'd have to manage (with regards to privacy, encryption, cleaning up when deleting the wallet, etc).

**Comment by linnutee** [comment]
This is one of several Pi related features that could be potentially added. I think it's best to keep them mapped out and tagged here, i'll also make notice of all of them so they can be looked at together in relation to each other. Don't recommend implementing oddly one by one. Can be rather quickly prototyped as UI wireframes first.

**Comment by alexlyp** [comment]
Added in recent styling updates
