### ISSUE TITLE
SPV enabling launch page

### ISSUE THREAD

**Issue by MariaPleshkova** [decred/decrediton#1755]
Preview: https://xd.adobe.com/view/7e93d6bd-7c03-4d24-6bc0-b6fca10a9a45-08a2/
Specs: https://xd.adobe.com/spec/76e88518-6127-4a05-5662-666c01547674-00d9/

Add SPV enabling launch page ( #1713 ). 
On the layout you can see hover effect for "Enable SVP" card. The choice gets applied when clicking on the card.

It uses the similar pattern as the "Privacy options" page does:
![image](https://user-images.githubusercontent.com/8841018/47807832-14be3f00-dd4e-11e8-9f18-4af932d15b76.png)

Also need to write a correct copy for it, as the current one is a placeholder (showed on the screenshot below texts that have to be changed)
![image](https://user-images.githubusercontent.com/8841018/47808053-9e6e0c80-dd4e-11e8-8b55-47b53742836b.png)

**Comment by alexlyp** [comment]
Can you attach the icons as well?

**Comment by MariaPleshkova** [comment]
@alexlyp [svp icons.zip](https://github.com/decred/decrediton/files/2536079/svp.icons.zip)

**Comment by RichardRed0x** [comment]
There's a typo in the image (SVP).

Here are some initial short suggestions:
- SPV enables a client to identify and verify transactions related to a wallet without downloading the entire blockchain. Using SPV involves a trade-off of some privacy for convenience. The nodes from which blocks are requested can infer that the requester (you) operates a wallet with transactions in those blocks. Decred's SPV implementation uses compact filters and requests blocks over the P2P network, rather than relying on a single node - making it less likely that privacy will be compromised in any significant way.

Enable SPV:
- SPV will allow your wallet to sync more quickly because it will not download and process the full blockchain.
Disable SPV:
- SPV trades some privacy for convenience, the nodes from which blocks are requested can infer that the requester (you) operates a wallet with transactions in those blocks.
