### ISSUE TITLE
Only display integers as atom balances

### ISSUE THREAD

**Issue by szpasztor** [decred/decrediton#1780]
When "atoms" is selected as the display unit, some balances might appear as decimal values instead of integers due to the limitations of the double-precision 64-bit format IEEE 754 values that JavaScript uses to store numbers. 

Change the `Balance` component so that it rounds values in such cases to the nearest integer.

**Comment by matheusd** [comment]
While I think this is reasonable and a simple change, this is not an issue for most wallet operations and at least a warning or something should be output when encountering floating point atom values.

The reason for this is that all internal wallet operations and the internal representation for any dcr amounts are performed using atoms and JS numbers are safe for storing and passing around these types of values due to [Number.MAX_SAFE_INTEGER](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER).

Given `MAX_SAFE_INTEGER` is ~`90e14` and the maximum dcr atom amount is [21e14](https://github.com/decred/dcrd/blob/v1.2.0/dcrutil/const.go#L17) we can be sure that no atom amounts in regular wallet operations (values in transactions, account balances, etc) will ever require decimal atom amounts.

Now, obviously this isn't true for _operations_ using atom amounts: for example, the total amount staked stat may eventually surpass MAX_SAFE_INTEGER (given that it's an accumulation of a historical amount) or if we have to perform a division (say, send an equal amount from 1000 atoms to 3 different addresses) than we do need to somehow deal with floating point atom amounts. However, in these situations the rounding problem needs to be dealt with **in the operation** (not only on the display stage). Going back to the division example, you have to actively decide what to do with the remaining atom (send to a miner? send to one of the addresses? send to a change address?).

That's why I mentioned in the review of #1764 that the rounding should be performed on the input data being fetched from dcrdata: so that internally the representation in atoms is consistent. Ideally, the dcrdata api should have been returning the balance amount in atoms instead of in dcr. Or instead of simply multiplying then rounding we can perform a more complex conversion from the input json to the atom amount (eg: converting to a string then dropping the ".", or converting to a BigDecimal, performing the multiplication, then converting back to a number if that is able to deal with the precision problems).

In the long run, we could have a specific type for representing dcr amounts that deals with these kinds of situations (converting from various representations, allows performing calculations, etc), but this will be a major undertaking.

My point in all of this is that, while suppressing the fractional part of numbers when displaying atom amounts is fine, the fact that a given atom amount is being passed around with a fractional part is a red flag that the previous calculation that produced this number needs to actively deal with. Hiding this fact in the display stage may end up biting you in the future.

**Comment by szpasztor** [comment]
Your point makes complete sense. Just for the record, the specific situation where I spotted the floating error was in displaying the treasury balance which is ~`58e12` as I'm writing this, so the issue here is with multiplication, not being out of the safe bounds. 

With all these in mind, here's my proposal:
- close this issue
- I'll implement a correct but slightly more complex conversion in #1764 (right after the value is fetched from dcrdata)
- in the long run: implement the new, DCR-specific currency type (maybe open a ticket/add to backlog?)

This way all displayed amounts would remain correct with reasonable development time spent, and there'd be plenty of time to design & implement the proper data type before new floating problems become relevant (eg. total staked amount). What do you think?

**Comment by matheusd** [comment]
Sorry for letting this slip.

Yeah, that approach sounds fine.
