### ISSUE TITLE
Restore existing wallet does not automatically request stakepool api key

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#1888]
I believe the functionality was added here: decred/decrediton#1410

However I have just restored an wallet using the latest code and I am not getting a prompt to add an API key. Tested with SPV mode both enabled and disabled.

**Comment by matheusd** [comment]
Yeah, that is a consequence of the changes in the wallet startup sequence: instead of individual steps performed by decrediton (which we could hook into), the wallet now goes through all steps automatically.

We're still trying to figure out the best way to accommodate this when using this new functionality.

**Comment by jholdstock** [comment]
No longer relevant

**Comment by jholdstock** [comment]
No longer relevant
