### ISSUE TITLE
"Estimated time left in x minutes"

### ISSUE THREAD

**Issue by RichardRed0x** [decred/decrediton#1894]
When the blockchain is syncing, the message reads "Estimated time left in x minutes", the "in" should not be there. I guess it was supposed to be "Estimated time left: X minutes"

**Comment by matheusd** [comment]
I've double checked to make sure, but the "in" comes from the locale data that our internationalization library (https://github.com/yahoo/intl-relativeformat) uses, so it's pretty much impossible to remove the "in" without rewriting the entire locale data for english (and all other applicable languages).

Do you think it's enough to re-write the prefix, so that the "in" makes more sense (eg: "Ending (in XX minutes)"?

**Comment by RichardRed0x** [comment]
That would be fine, how about something more descriptive like "Blockchain download complete in"?

**Comment by matheusd** [comment]
I guess that works. For reference, these are the suffixes that the intl library generates for english:

```
now
in 10 seconds
in 1 minute
in 4 minutes
in 1 hour
in 4 hours
in 18 hours
tomorrow
in 2 days
in 17 days
next month
in 2 months
in 6 months
next year
in 2 years
```
