### ISSUE TITLE
[1.4.0-rc] Mismatched PIN input for trezor/decrediton.

### ISSUE THREAD

**Issue by dnldd** [decred/decrediton#1932]
Trezor shows a number pad for pin input while decrediton shows an alphabetic one. Would be best to mirror the trezor to avoid confusion.
![pin_input](https://user-images.githubusercontent.com/1281030/50220062-25238b00-0389-11e9-9987-f2c1aa3ca6fa.jpg)
![wallet_pin](https://user-images.githubusercontent.com/1281030/50220093-3a98b500-0389-11e9-9cdf-f14468be8276.png)

Also I think a smaller pin modal (width of the pin input, padded, with the input field and buttons below the pin put) centered would be better presentation.

**Comment by matheusd** [comment]
We can discuss this with the design team, but personally I implemented it this way because (as a novice trezor user) it felt weird to try to match the "1" in the software keyboard to the (eg) "9" on the trezor view.

In other words, if you actual trezor pin is "1234", due to randomness of the keboard that trezor generates at every pin entry, you'd need to type (eg) "8217". Trying to type that on key physical keyboard seems to confuse things, so I opted to display the input as letters instead of numbers so that there's no ambiguity.

**Comment by dnldd** [comment]
Noted, didn't think of the randomized key layout at first. Knowing the order of the randomized keys would defeat its purpose. "Perhaps we should consider just showing '●' for the input pad keys to avoid mapping characters to numbers. The trezor wallet does this as well, users would be more used to that pattern.

![pin_input_trezor](https://user-images.githubusercontent.com/1281030/50230152-08e11780-03a4-11e9-902a-4c0b901fdb02.png)

**Comment by matheusd** [comment]
Ah, cool. I think they might have updated this recently, because I could swear when I started working on it they showed numbers instead of these dots.

This does make sense for mouse users, but prevents (or makes it harder) entering the pin when you only have a keyboard.
