### ISSUE TITLE
Visual Design: Governance subviews tweaks and bug fixes

### ISSUE THREAD

**Issue by linnutee** [decred/decrediton#1945]
Preview: https://xd.adobe.com/view/fefd1452-fc57-4418-6610-736fa70425db-88cc/
Specs: https://xd.adobe.com/spec/fb0fd24e-9c3c-4854-656e-c7bc8332e18d-8d3e/

Governance view/all proposals: 
- I've reduced the new proposal row styling to a much more minimal variant, as the previous got quite bloated. Only a 5px stroke on the left side for new proposals, instead of full row coloring.
- New item number ticker for `Under Vote` and `Under Discussion` seems to be missing a fill value. Besides the stroke around it, the circle also needs a solid fill of `#8997A5` in order for the white background to show. ![](https://user-images.githubusercontent.com/17774057/50377719-0d6b3180-062b-11e9-90ed-55bc5d9606ac.png)
- For individual proposals view, added a white background solid to the proposal content area to make the view more cohesive. There is also a 1px seperation between the high level details and the proposal content. 
- The individual proposal view is currently partially implemented, as the content area text styles seem off/missing and the text area container is also too long in width (should be 380px). 
- All bolded text styles should be with Source Sans Pro SemiBold. There should not be any full Bold in Decrediton, only SemiBold.
- Added a state for "Proposal not yet in Voting stage." Icon: [chatBubbles.svg.zip](https://github.com/decred/decrediton/files/2705465/chatBubbles.svg.zip)
- Added a disabled state for the expanded consensus cards. When a consensus vote has been finished, it should be disabled (currently some of the elements are in active states, some not). 
- Updated the expanded consensus cards `My Voting Preference` slightly to make it consistent with the same function in proposals (not sure if it's fully implemented there). In the current release, the radio buttons are slightly off, having too thick strokes. (Note: there should be 5 types of radio buttons now: blue for consensus changes, orange/green for proposals, default grey/blue for settings or generic use and disabled state).

**Comment by vctt94** [comment]
I can fix these

**Comment by linnutee** [comment]
- Abandon tab: don't think this was even in the first place. Coming to grouping logic, as "finished" proposals is a group containing both approved and declined ones. I think the abandoned ones could be somehow worked in there as a reference to proposals.decred.org rather than bloating the UI. If there's any strong considerations to include abandoned proposals in a more prominent manner as now, then can work on this further. Also re: to this point, ideally the categories should match in pigui and decrediton, there was an issue with some discussion around this – will try to find. Any updates obviously should reflect here.
- The blue border indicates new proposals that the user has not viewed yet. Believe this has another styling atm, as the whole row is blue. 
- The idea behind the start staking button was to incentivize users to look into staking. So this should be shown only if the user has not setup any VSP yet.

**Comment by vctt94** [comment]
I made some interactions in this code and I believe I still have some design questions I did not really catch.

- I think an abandoned tab makes sense because we can have `pre vote`, `active vote`, `finished vote` (which includes approved and rejected proposals) and `abandoned`. This way none of the tabs will have too much information and this gets closer from how the politeia's design looks right now.
After the redesign: https://test-proposals.decred.org/ they now have `In Discussion` `Voting` 
`Approved` `Rejected` `Abandoned`.
We do have an issue about it: https://github.com/decred/decrediton/issues/2015, so I think it makes sense if we change for the same nomenclature, but I like the finished tab merging approved and finished proposals, as the screen already have too much information.
What is your opinion on that?  

- It would be good if we have notifications showing a proposal has already been voted. Right now they only are distinguishable when they are new proposals:
![image](https://user-images.githubusercontent.com/15069783/65393215-61d74500-dd54-11e9-930d-ef4f45ba2997.png)
 I made this issue a while go about that https://github.com/decred/decrediton/issues/2076 

- Okay, that makes sense

**Comment by linnutee** [comment]
Yep these should just match. Was considering earlier to try make the abandoned less prevalent, but it would get pointlessly complex. 

Voted/not voted proposals are somewhat minimally distinguished by the circle on the left side of the progress bar. This turning either green, orange or being grey if not voted. If you didn't notice this, tells me i'll need to make something a bit more obvious. As during the initial design, did question whether it risks being misunderstood.

**Comment by vctt94** [comment]
I did not noticed at first, but now that you said it looks really obvious. We can go with that approach and if we notice people struggling with it, we can change.
