### ISSUE TITLE
[Tickets] Unable to load more tickets

### ISSUE THREAD

**Issue by Guang168** [decred/decrediton#1958]
Under Tickets - my tickets, when filters set to all tickets i can scroll down and view older tickets. 

When filter set to voted and live, text showing "Loading more tickets..." with bouncing stakey but nothing gets loaded for very long time.

**Comment by Guang168** [comment]
update: 
when filter set to all, sort by oldest its not able to load. 
when filter set to all, sort by newest it loads very quickly and i can scroll down to view more tickets. 

when filter set to live, sort by oldest it loads very quickly and i can scroll down to view more tickets. 
when filter set to live, sort by newest its not able to load

when filter set to voted, both sort by newest and oldest doesnt work.

**Comment by matheusd** [comment]
Not sure whether you're testing from master or from the rc1. I believe rc1 was not built with #1890 in, so behavior may be different.

Due to dcrwallet not having an index of tickets per status per timestamp, we end up having to scan the transaction list to show the tickets by their correct event order, so some operations are expected to take a long time to complete on large enough wallets.

In particular:

- Live tickets when sorting by old (if you have a large number of transactions but the live tickets are only very new - which is a likely situation to be in), then you'll effectively need to rescan all transaction to find the latest live tickets

- Missed/revoked/expired when none exist: same as above

However, voted tickets should usually complete and not take very long to do it, given that is the most common situation for tickets.

We can slightly improve the UX feedback by adding a linear progress and a cancel operation, and we could add a date range selector, so that the user can narrow down and speed up the search, but that's about it without further changes to dcrwallet.

**Comment by Guang168** [comment]
Follow up on that after discussion with @matheusd it has something to do with "Height of the window for searching for new transactions" 

After i resize it to single column, all ticket loads and im able to scroll down to the end. When its maximized window showing multiple column, some ticket doesnt load. 

Below screenshots for reference.

![screen shot 2018-12-27 at 6 05 29 pm](https://user-images.githubusercontent.com/43533453/50476178-25afc780-0a02-11e9-807b-4cacde603d7a.png)
![screen shot 2018-12-27 at 6 05 20 pm](https://user-images.githubusercontent.com/43533453/50476180-28122180-0a02-11e9-9517-ed2c8999f3a0.png)
