### ISSUE TITLE
[1.5.0-rc1] Visual Design: Field dropdown spacing

### ISSUE THREAD

**Issue by hqnnes** [decred/decrediton#2295]
Preview: https://xd.adobe.com/view/e781e497-d2cc-4c86-5642-958d2db4cd2f-91b0/
Specs: https://xd.adobe.com/spec/7a704ab7-92f9-4d43-474f-ad952a6a2b5e-0c41/

The dropdowns have a spacing surplus. Sidenote: the field dropdowns are going to be addressed in an upcoming issue.

**Comment by bgptr** [comment]
@hqnnes It is because I skinned the dropdowns in #2239. The problem is the white arrow on white background. Just to see clearly what is happening:
![image](https://user-images.githubusercontent.com/52497040/68710668-417b7800-0598-11ea-982f-717e32b4c837.png)
Before this PR I think there was only one dropdown version and I suppose we need at least one more. What do you think?

**Comment by hqnnes** [comment]
I see what the problem is. There are 2 types of dropdown components used in the Decred UI. 
First type is the normal dropdown fields which have square corners and a stroke in the bottom half. These are the more commonly used dropdowns. 
The second is the context menu dropdowns, they have rounded corners and a notch on top. These are used in the context menus (e.g. Tx History filter). The normal dropdown fields are visually consistent with the input fields whereas context menu dropdowns are visually consistent with the context menu buttons.

 Example of the two types: https://xd.adobe.com/view/80199368-5a7c-4c3d-6d9a-994ac574ce55-f628/

**Comment by bgptr** [comment]
Thanks, this is what I also see.
Meanwhile, I sent a PR, which is a quick solution for rc1. 
We can work on dropdowns globally in your upcoming issue.
