### ISSUE TITLE
Visual Design: Configured VSPs view

### ISSUE THREAD

**Issue by hqnnes** [decred/decrediton#2305]
Preview: https://xd.adobe.com/view/61bcdbfa-d996-4c18-5151-daa29d4a60a0-178d/
Specs: https://xd.adobe.com/spec/0c81a23a-afbb-4b92-6b43-f4dc83b6945e-7ab0/

The script is a regular script component with additional fade and lesser line-height to show the next line better.

**Comment by s-ben** [comment]
Is this issue still in play? Thinking of tweeting it out on the [Good First Issues (GFI) twitter](https://github.com/decred/decrediton/issues/1992) accnt.

**Comment by vctt94** [comment]
Yeah, I believe it is. But right now we do not have this view, so I think @hqnnes may have added it to the wrong place. 

Is it supposed to be at the purchase tab in tickets views? How can we get there?

**Comment by linnutee** [comment]
These are the staking setting specific views. I believe they didn't have any visual design whatsoever before. So when accessing the stakepool settings, which is in the purchase tickets tab.

**Comment by linnutee** [comment]
Small update to this one, just shooting the icon and a screenshot to illustrate. vctt pointed out the misuse of X close here, as that's typically for back not deleting. So for consistency, please replace the X icon with the trashcan icon. The icon could also be aligned against the info icon + the text, rather than being in the corner like close. At 32px with boundingbox: 

[deleteVSP.svg.zip](https://github.com/decred/decrediton/files/4650649/deleteVSP.svg.zip)


<img width="1023" alt="Screenshot 2020-05-19 at 16 12 29" src="https://user-images.githubusercontent.com/17774057/82330464-8ec71f00-99eb-11ea-9fe5-f6dfe229ca4b.png">

**Comment by guilhermemntt** [comment]
Thanks @linnutee !
