### ISSUE TITLE
Scroll down 'broken'

### ISSUE THREAD

**Issue by rodrigondec** [decred/decrediton#2314]
I'm using Deepin linux (debian). I have Decrediton 1.4.0 installed.

The scroll works perfectly fine when using the Decrediton without the window maximized (print below)
![image](https://user-images.githubusercontent.com/3301060/69116752-30d17300-0a6c-11ea-8941-e55d0b5ee88b.png)

Whilst the when I maximize the Decrediton window, the scroll doesn't "go all the way". It doesn't recognize my deepin toolbar and the rest of the window stays behind it.
![image](https://user-images.githubusercontent.com/3301060/69116923-c0772180-0a6c-11ea-930b-726eb859ff1e.png)

**Comment by vctt94** [comment]
Decrediton 1.4.0 does not support responsiveness properly. I am not able to reproduce this in our release candidate. 

If you can give it a try and reproduce it with our release candidate or close the issue otherwise would be much appreciate.

Here is a link for our release candidate binary: https://github.com/decred/decred-binaries/releases/tag/v1.5.0-rc1

**Comment by rodrigondec** [comment]
Yes, responsiveness worked properly on 1.5.0-rc1.

Ty
