### ISSUE TITLE
[1.5.0-rc2] Send Transaction screen aethestics

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#2337]
Compare 1.4 and 1.5 below:

![send](https://user-images.githubusercontent.com/6762864/69405118-cc761400-0cf6-11ea-9a5f-6942e334e497.png)
![Screenshot from 2019-11-22 07-07-54](https://user-images.githubusercontent.com/6762864/69405134-d4ce4f00-0cf6-11ea-820b-1f643e506428.png)

- The bottom of the gray "Details" panel does not align with the bottom of the white panel, but they are close enough that they give the impression they should be aligned.
- The "+" icon looks strange with blurred edges, doesnt seem to fit the rest of the aesthetic. Also the color doesn't match the other icons. The white "+" is really small compared to the total size of the button.
- The small "Details" heading seems unnecessary, and is located in a strange position

Personally I think the 1.4 version looks significantly better and 1.5 feels like it has regressed

**Comment by vctt94** [comment]
The Misalignment and blur icon are indeed wrong. About the "details" header, this is how it is supposed to be. 

We can have @linnutee 's opinion here, but this is how it is supposed to look. From the original issue: https://github.com/decred/decrediton/issues/1947

**Comment by linnutee** [comment]
The reasons behind the details change are due to responsive views + the send button going to the right, as that leads to instances where the previous separated placement of the TX details isn't optimal anymore in all cases. 

Having it as a section of the sending component gives a simple solution. Do agree to the "details" component being slightly unusual due to alignment / grouping distance, but it does optically fill up the container well. Simple improvement might come down to optimizing the container width + way that data is presented. Or would also consider whether there's any useful matters to solve with this.

I'll list it as something to think about how to improve on dcrdesign repo.
