### ISSUE TITLE
[redesign] Eligible tickets section in proposal details page

### ISSUE THREAD

**Issue by amassarwi** [decred/decrediton#2428]
See screenshot:
![image](https://user-images.githubusercontent.com/10324528/75542746-b0ce8800-5a20-11ea-9e8d-b1660ced9805.png)

**Update:** 
We ended up getting new design for the eligible tickets section, see comment below: https://github.com/decred/decrediton/issues/2428#issuecomment-606018117

**Comment by linnutee** [comment]
Following up on this one, there's a few issues to consider in the layout. 

1. Wallets Eligible Tickets seems a new component, bit out of sync with the rest of the common components. I've created an example using a accordion within a separated row. This gives it a clearer separation and a bit more harmonious fit. 

Also the copy "Wallet Eligible Tickets" is a bit odd, would propose something in lines of `My Tickets, Eligible for Voting: <ticket-sum> total`
or `Tickets Eligible for Voting: <ticket-sum> tickets in wallet` for example.

If you could also include an example of how the tickets look like when expanded, i'll provide feedback and updated example if needed. 

2. "See proposal comments" on Politeia buttons placement. The problem with the text running too close to the button comes from the text being in full width of the container. The proposal contents text area has actually been in much smaller width in the UI designs, due to the reasons of legibility. Around around 50-70 characters per row makes for an optimal length, anything longer increases the reading difficulty. I assume this was made full length to decrease the vertical height of the page as the proposals are usually quite long. 

So this bit can be addressed by limiting the text area just about 10px smaller in width off the left side of the button. I've reduced the line height quite a bit down to 15px, this should make the text vertically more compact. 

Specs/preview: https://xd.adobe.com/view/cb98a967-40d1-4dc6-568f-90fccf53d9dd-bda9/

**Comment by amassarwi** [comment]
Thanks for the specs @linnutee, looks clean.
Regarding the expanded mode. I've this cropped screeshot of the expanded tickets list not sure if it's good enough:
![image](https://user-images.githubusercontent.com/10324528/77005694-873eb780-6961-11ea-8013-3e239ce013f2.png)
AFAIR @vctt94 has testnet wallet with many voting tickets and may be able to share a better screenshot for the expanded mode.

**Comment by vctt94** [comment]
This is how it looks closed:

![image](https://user-images.githubusercontent.com/15069783/77021404-56f91800-6965-11ea-901b-e5cdb423ac69.png)

This is how it looks openned: 
![image](https://user-images.githubusercontent.com/15069783/77021420-64ae9d80-6965-11ea-9c52-a0a2e3b3797d.png)

Right now it only shows the ticket number and its hash. The rows are not clickable

**Comment by linnutee** [comment]
Thanks for sharing, i'll get some tweaks over for the rows styling as well.

**Comment by linnutee** [comment]
Prev/Specs: https://xd.adobe.com/view/3e1ba567-4d17-45b7-4365-b70232163f0a-482a/

I would try to incorporate the updates from My Tickets (https://github.com/decred/decrediton/issues/2262) view as part of this also. The use of a table illustrates each ticket more clearly as well possibly provides somewhat improved insight on the voting. 

Up for discussion is what's the details worth including there: 
Price + Tx hash + Account + Purchase time seems like a sensible combo to help distinguish the tickets.

On 3rd slide included "Vote Preference" - if I understand correctly the actual offchain votes on Pi can't be tracked here. However I think it might be still worth repeating the set preference on the tickets, as this will help to illustrate the point that all of these tickets are affected and are voting. On third slide also included an info icon next to that, which can be used to describe what's technically going on (info modal/needs some copy then). 

On finished proposals, if possible the same accordion should show which tickets were affected.

On ticket row follow-up, not quite sure if these tickets can follow-up to the relevant Transaction Views, if they can they should. If not, the row should highlight only the Tx hash and open it in the block explorer.
