### ISSUE TITLE
Ticket buyer prompts early confirmation

### ISSUE THREAD

**Issue by zubairzia0** [decred/decrediton#2494]
Noticed the ticket buyer prompts a  "successfully started" even if the wrong passphrase is entered. I think the passphrase needs to be checked before the confirmation message. 

![tix1](https://user-images.githubusercontent.com/23157945/82742091-817d9d80-9d27-11ea-88ba-c46fba6402d1.png)
![tixbuyerconfirm](https://user-images.githubusercontent.com/23157945/82742093-83dff780-9d27-11ea-95e0-93b29538f7fe.png)

**Comment by zubairzia0** [comment]
I mentioned before that I will work on this however I am unable to atm. Someone else can take this on.

**Comment by guilhermemntt** [comment]
I've checked this issue. It seems that the gRPC service does not receive any confirmation message if passphrase is correct. Otherwise, if it's wrong, Decrediton receives an error message from drcwallet. Due this issue, currently, the first message ("Ticket Buyer succefully started") is always displayed, even if Decrediton receives the wrong password message from dcrwallet asynchronously after that.
