### ISSUE TITLE
Restoring from seed does not restore the lightning wallet balance 1.5.1 (Linux)

### ISSUE THREAD

**Issue by hermanlim** [decred/decrediton#2527]
Not sure if this is a design feature/limitation of LND.

Made a second decrediton wallet on laptop from seed words used on main computer. Noticed that total balance was off slightly and that the difference was due to the LN wallet balance not being 'restored'.

**Comment by matheusd** [comment]
It's a design limitation of lightning. Due to it's nature of being a second layer solution, the data for a lightning wallet is necessarily not stored in the blockchain itself, so restoring from seed **does not** restore lightning data by default.

Lnd offers a special backup structure called SCB file which you have to backup and then use to restore data, but importing that is not yet exposed in Decrediton.

**Comment by matheusd** [comment]
PR #2535 will expose the SCB file location, plus allow the user to generate ad-hoc backups, verify them and restore the SCB file backup when creating a new LN wallet on a seed restored wallet.

I'll add some extended documentation on docs.decred.org on how exactly the backup process works and its limitations.

**Comment by xaur** [comment]
@matheusd is SCB a binary file and is it large? I wonder if the LN wallet data fits into the concept of standardizing non-seed data I described in https://github.com/decred/dcrwallet/issues/1731

**Comment by matheusd** [comment]
It's not large but it changes every time you open or close a channel, so it's might be faster changing than the proposed one for dcrwallet.
