### ISSUE TITLE
[governance] Improve politeia fail

### ISSUE THREAD

**Issue by vctt94** [decred/decrediton#2550]
Right now we are checking for errors when getting proposals, but we also need to throw errors when failing to fetch invetory as well.

If for some reason, the token inventory fails to fetch, we should alert the user. Right now it only spins indefinitely:

![image](https://user-images.githubusercontent.com/15069783/86023204-be614200-ba01-11ea-8240-306e9c13e6f8.png)

**Comment by victorgcramos** [comment]
on this!

**Comment by amassarwi** [comment]
@victorgcramos great mate.
I actually experienced another bug lately which could be related, if you open a wallet and navigate to the proposals list directly, the page hols on loading forever without even any error in console.

**Note:** Decrediton fetchs the proposals info when you open the wallet so I guess this bug happens when you navigate to the list before arrival of that information.

**Comment by vctt94** [comment]
fixed on https://github.com/decred/decrediton/pull/2571
