### ISSUE TITLE
Percent complete during block/header downloading

### ISSUE THREAD

**Issue by jcvernaleo** [decred/decrediton#271]
There are reports that the % given during a startup where the cmd line tools aren't fully synced either doesn't move at all or isn't accurate.  This should be investigated and fixed if confirmed.

**Comment by alexlyp** [comment]
So this was introduced due to fixing the ordering of wallet bring up.

StartRPC --> SubscribeToBlockNtfns --> FetchHeaders. 

With this new ordering we will need not do fetch header progress repeated calls.  Instead we will let the user through and come up with a new mechanism to determine if the wallet is "ready" or not.  We were thinking something similar to bitcoin-qt and show the user a rough idea of how far "back" they are. (2 weeks behind...)
