### ISSUE TITLE
Why is it syncing from a centralized source?

### ISSUE THREAD

**Issue by taoeffect** [decred/decrediton#284]
I'm noticing that it's only pulling the blockchain from `mainnet.decredseed.org`.

**Comment by chappjc** [comment]
That's one of 4 DNS seeds that return dynamic lists of actual nodes.  These nodes are not centrally controlled, merely tracked by the DNS seeds.

**Comment by taoeffect** [comment]
How is the data verified? I saw "checkpoints" mentioned in the terminal output, so I'm guessing the seed hashes are hard-coded into the binary?

Is there a document somewhere that explains how frequently these sort of manual checkpoints are/will be created? What the policy is regarding them?

**Comment by jcvernaleo** [comment]
The 4 DNS seeders (per network) are just there to help you find some nodes initially and they are hardcoded at https://github.com/decred/dcrd/blob/9f58376efca89bb164e684933076ad93bfa6f536/chaincfg/params.go#L452
You get no data other than node addresses from them so there is a fairly minimal amount of trust needed from them (as you still go to other nodes and validate what you get there).

The checkpoints are hardcoded in the code, generally one per release at https://github.com/decred/dcrd/blob/9f58376efca89bb164e684933076ad93bfa6f536/chaincfg/params.go#L486 

If for some reason you don't trust those, you can always download the chain without checkpoints:
```
dcrd --nocheckpoints
```
and confirm that the hashes in the checkpoint are correct and in your checkpoint free blockchain.  This probably is not worth it though since if someone can commit bad checkpoints to the code they can commit other bad things to the code.

**Comment by jcvernaleo** [comment]
Closing this issue since this in not related to decrediton and is really about dcrd.  And it looks like you already opened an issue there that supersedes this decred/dcrd#621
