### ISSUE TITLE
Declutter nav menu

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#2939]
Suggestion from @linnutee 

https://xd.adobe.com/view/e51f9efc-bb29-48b2-9158-d41870429ecf-b04c/
> The navigation has gotten overloaded. Since there’s LN and in some cases Trezor added, that sums up to 10 items. I would propose to drop Help and Settings from the main listing and place those into the bottom area as only an icon. Replaced settings icon with the “gear wheel” metaphor as that’s more known. Alternatively the subpages under Help could be placed under Settings to have only 1 one icon there? Bit less loaded this way.

> I’ve made a combined component for the peer count and block sync. This is accompanied by the block icon, if synced has a checkmark next to it, if not has X and during rescan can display the block loop animation https://lottiefiles.com/20515-block-loop … Peercount can be right below this. SPV I’m not sure what’s the reasoning on having there, as well is really odd man out when it comes to the component/placement. If anyone can explain that, I’d have more insight how or where to work in the indicator. Doesn’t necessarily need to be even the menu imo. Alternatively, all three items (Blocksync, peercount and SPV/Non-spv can be a click-through component in the bottom left (ie. only one is shown at a time and others are shown on clicking through them as sort of carousel … can prototype an example).

**Comment by amassarwi** [comment]
Can do

**Comment by linnutee** [comment]
Updated nav specs here: https://xd.adobe.com/view/03629089-8302-4b84-a964-2fb4f48356dd-5631/

I've worked out indicator icons for SPV and No SPV. These should just display the same text on hover as it happens now with the symbol. Also included an icon if the block isn't synced. 

Recommend having only Settings in the bottom right edge and positioning the subpages in "Help" (Sources, Tutorials, Logs) as additional pages in Settings. I recon when we get some additional tutorials added, accessing those can happen within the wallet at relevant places, rather than from nav. 

Selected nav item styling also needs a minor fix: the white bg solid has gone missing from behind the selected nav item. 

<img width="805" alt="Screenshot 2020-11-16 at 00 02 46" src="https://user-images.githubusercontent.com/17774057/99198107-1b864600-279f-11eb-8659-f188e7fcff52.png">

**Comment by amassarwi** [comment]
Thanks @linnutee 💯 will work on that next

**Comment by jholdstock** [comment]
> the white bg solid has gone missing from behind the selected nav item.

What colour should this be for darkmode?

**Comment by linnutee** [comment]
Active/select is`#2F4D8C` for dark parts and `#99C1E3` for light parts.

**Comment by linnutee** [comment]
@amassarwi Svg package with all the dark mode icons: [decrediton - navigation assets - dark mode - 171120.zip](https://github.com/decred/decrediton/files/5554347/decrediton.-.navigation.assets.-.dark.mode.-.171120.zip)

Preview: https://xd.adobe.com/view/ff549c6a-f980-4e94-98f7-0d1ac7acf905-aa07/

**Comment by amassarwi** [comment]
@linnutee thanks mate 🚀
