### ISSUE TITLE
New nav icons

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#2940]
@linnutee suggests some icon changes:

https://xd.adobe.com/view/e51f9efc-bb29-48b2-9158-d41870429ecf-b04c/

> Also created icon for Lightning … current one is a symbol version not intended for this small use.

> For Privacy also created a new icon. As Privacy is a far more important feature than the stuff in Security Center, that should be the leading metaphor in nav. Lock is fine for security, but for Privacy/Mixing, the incognito metaphor makes more sense. This gives nice ground to create derivate icons for mixing accounts, transactions and such.

**Comment by jholdstock** [comment]
I'll take this

**Comment by linnutee** [comment]
[decrediton - navigation assets 151120.zip](https://github.com/decred/decrediton/files/5543178/decrediton.-.navigation.assets.151120.zip)

Added all the assets here and updated preview with specs. Since it's going to take some time to create the animated vers for LN and Privacy, worth to assess if going with stills for only those two or using stills for all makes more sense in mean while. Keep track here: https://github.com/decred/dcrdesign/issues/234

Making note that i've updated the icons sizes and colors slightly. We can drop using the default state with #8997A5 and #091440 and rather only use the higher contrast selected/active state with #091440 and #091440. This way the contrast is better. Also bumped the icon size from 20px to 22px (bounding box)
