### ISSUE TITLE
wrong timestamp format

### ISSUE THREAD

**Issue by vctt94** [decred/decrediton#2968]
I noticed this time in one of my votes: 

![image](https://user-images.githubusercontent.com/15069783/99586940-24596080-29c7-11eb-9ecc-093e4bc54467.png)

It was supposed to be 00:29.

**Comment by amassarwi** [comment]
on it

**Comment by amassarwi** [comment]
I have investigated the issue and it seems related to https://github.com/decred/decrediton/issues/2968, with recent chrome versions there is additional formatting option `hourCycle` to show time like `00:29` instead of `24:29` which is currently not supported by react-intl, the suggested workaround and according to the PRs linked to that issue from other react projects use native `Intl.DateTimeFormat` instead of react-intl's `formatMessage`

Something like:

```
const options = {
          hourCycle: "h23",
          hour: "numeric",
          minute: "numeric",
          second: "numeric",
          timeZone: "UTC" // in our case this should come from settings
        };

        const timeFormatter = new Intl.DateTimeFormat("default", options);
        const time = timeFormatter.format(txTs);
```
