### ISSUE TITLE
Implement tspend vote choice selection

### ISSUE THREAD

**Issue by matheusd** [decred/decrediton#3184]
Requires https://github.com/decred/vspd/issues/234

This will be needed once (if) the treasury agenda activates, so that stakeholders can make a choice regarding approving/disapproving tspends.

Ideally, a review of the tspend should be fetched from Politeia so that stakeholders can make an informed choice.

**Comment by jholdstock** [comment]
decred/vspd#234 requires decred/dcrwallet#2051

**Comment by xaur** [comment]
> Ideally, a review of the tspend should be fetched from Politeia so that stakeholders can make an informed choice.

I think it should be CMS and not Politeia. Or Politeia could cache it to not have CMS bombarded by wallet requests. But in any case CMS is the data source I think.

In any case, the bigger problem with the "informed choice" part is that there is almost no infrastructure to serve that data. Afaik, at the current stage the only goal was to "decentralize custody" without providing any information what stakeholders are voting on. Since the very [proposal](https://proposals.decred.org/proposals/c96290a) 2 years ago and to this date I've seen no backend changes, UI mockups, or even discussions on how it should work.

With that in mind, I think this issue should be focused on exposing tspend vote choices, and a new one should be created for the getting informed part where stakeholders could learn what they're voting on.

**Comment by xaur** [comment]
"What is being voted on" partially covered by #3762.
