### ISSUE TITLE
[trezor] support empty passphrase on passphrase-enabled wallets

### ISSUE THREAD

**Issue by matheusd** [decred/decrediton#3460]
The passphrase modal currently requires a non-empty passphrase, but when using the trezor passphrase feature, you might be using a wallet with an empty passphrase (the "default" trezor wallet).

**Comment by JoeGruffins** [comment]
I'll do this.

**Comment by JoeGruffins** [comment]
@matheusd It seems password encryption isn't even working on my trezor atm... Will try updating my firmware.

**Comment by matheusd** [comment]
Yeah, after enabling pwd protection you need to disconnect then reconnect the wallet. Would be useful to have a notice about that as well (e.g. blocking the trezor actions until the device is cycled)

You have a model T, right?

**Comment by JoeGruffins** [comment]
I believe the reason we need to disconnect is because the current wallet we are using is the default. What would really be good is a way to reset the connection, so that trezor (T at least) would not need to be unplugged, and would ask for a password upon the next request of sensitive data. Unfortunately, there does not seem to be any way to cleanly shut down, or re start the trezor transport. Maybe asking the user to yank the device is correct?

**Comment by matheusd** [comment]
> Maybe asking the user to yank the device is correct?

Yes, I believe that's the correct way to go about it (asking the user to unplug and re-plug the device after certain operations).
