### ISSUE TITLE
Remove legacy VSP ticket purchasing

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#3586]
All legacy VSPs are closed and no longer accept new tickets purchased from Decrediton, therefore the legacy VSP ticket options can be removed.

- Remove the form to purchase legacy VSP tickets
- Check through the UI to remove any other references to legacy VSPs
- Ensure legacy tickets are still tracked correctly in ticket history lists
- Ensure decrediton is no longer calling dcrwebapi endpoint https://api.decred.org/?c=gsd

**Comment by xaur** [comment]
If someone forks [dcrstakepool](https://github.com/decred/dcrstakepool) and patches it to work with all the new stuff, having a way to activate legacy ticket purchasing may help a few users to avoid running custom Decrediton builds.

As of writing, there are 184 legacy tickets making 0.45% of the ticket pool and worth ~$3.6M. I think when dcrstakepool stops working it _may_ trigger some people to team up and hire a dev to patch it, so that those who really want to keep using it could do so.

I think this is all very unlikely to happen, just wanted to mention the side effect of actually _removing_ the feature instead of hiding it.

On the other hand, if we keep it hidden, we kind of commit to test and maintain it in a working state, which is an extra cost.
