### ISSUE TITLE
User cannot log in if he has existing wallet without public passphrase

### ISSUE THREAD

**Issue by Dyrk** [decred/decrediton#39]

**Comment by alexlyp** [comment]
Known issue that will be taken care of

**Comment by jrick** [comment]
Just to clarify, wallets always have a public passphrase, but if one is not explicitly specified an insecure default is used instead.

That said we shouldn't need to care about what other existing wallets are found in ~/.dcrwallet, %localappdata%/dcrwallet, etc. because the plan is to start dcrwallet from decrediton and run it out of decrediton's application data folder (the same way paymetheus also works).

**Comment by jcvernaleo** [comment]
@jrick yep, and I am working on that in #41 so I'm going to close this issue.

**Comment by jcvernaleo** [comment]
Actually I'll wait and close it with the PR when it goes in.

**Comment by Dyrk** [comment]
@jcvernaleo is there any plan to reduce the size? Out of the box, it's already 1 GB (without blockchain, only grpc and decrediton files)

**Comment by jcvernaleo** [comment]
I believe that production builds with electron are much smaller.  So hopefully when there are actual packages (.tar.gz for linux and ,app for macOS) they should be much smaller.

**Comment by jcvernaleo** [comment]
@Dyrk just curious how you are getting 1GB.  For me:
```
jcv@triforce decrediton $ du -sh
510M    .
```

That is still huge, but not quite what you have.

**Comment by Dyrk** [comment]
@jcvernaleo 1 gb is for both folders `decrediton` + `grpc` (in macOS)

**Comment by jcvernaleo** [comment]
Okay, I didn't think to count the grpc one.  We will address the grpc issue at some point too, but this early in dev, I'm fine with the huge size.
