### ISSUE TITLE
Error message when trying buying ticket: This script is not redeemable by this wallet.

### ISSUE THREAD

**Issue by lbiazao** [decred/decrediton#433]
After update my decrediton wallet to 1.0.3, I have tried to buy new tickets using the same stake pool I was using before I get this error:
This script is not redeemable by this wallet.
<img width="881" alt="screen shot 2017-06-13 at 04 33 21" src="https://user-images.githubusercontent.com/5401274/27077880-f446a5de-5007-11e7-8c1f-a4312ca727d3.png">
The same error occurs when trying to update the script:
<img width="480" alt="screen shot 2017-06-13 at 06 59 44" src="https://user-images.githubusercontent.com/5401274/27077804-b63ce62c-5007-11e7-8c9c-32b2c47ca3d3.png">

**Comment by jrick** [comment]
have you ever seed restored this wallet? If so, when you previously set up the stakepool with the wallet, did you use a different voting account which is not in this wallet?

**Comment by lbiazao** [comment]
I have already seed restored recently to solve the problem with the stuck transaction, I have never used a different voting account it was working properly until last cycle with payment 47,... per ticket. 
After that I just installed the new version of Decrediton from 1.0.2 to 1.0.3....

**Comment by lbiazao** [comment]
@jrick I have already used the same stakepool account to a different Paymetheus seed and use the same pool script in this Decrediton wallet that has a different seed from Paymetheus. May this be the problem?

**Comment by jrick** [comment]
If you created a voting account (like the instructions used to say to do) when setting up the pool in paymetheus, and you don't see that account in your decrediton wallet, you should create it manually.

Your key from the 1-of-2 multisig voting script could be in that account in which case it would need to be recreated in order for the script to be spendable by you.

**Comment by lbiazao** [comment]
@jrick I see you have nice words for me, I don't quite understand what you are talking about multisig voting.... I was using in 1.0.2 version and it was working properly.

**Comment by jrick** [comment]
stakepools use multisig voting.  both you and the stakepool can vote.  this is possible because voting rights is given to a 1-of-2 script where only one of your or the stakepool's private keys is required to create votes or revocations.

It's important that you remain in control of your own voting rights, otherwise stakepools could refuse to create votes and extort you for revocations.  This is why the wallets are checking that your own wallet also has voting rights.  This is a new check and it is why you are seeing the warning above.

If your public key that was used to create the the voting script is in an unrecovered account, your wallet will not know that you actually could create the vote/revocation.  So, if you used a used a separate voting account when setting up the pool earlier, and this account hasn't yet been created by the seed-restored wallet, your wallet will believe it is unable to redeem the output (which, at this time, is correct, but can be resolved by recreating the account).

It's also important to know that accounts are numbered internally, starting at 0.  The default account is account 0.  If you only had this default account, and then created a new voting account earlier, the voting account would be account 1.  You also will need this same account 1 in your current wallet, but it doesn't have to be named the same thing.

**Comment by lbiazao** [comment]
I have tried to create a new stakepool account but my decrediton stake pool scripts keep configured in the system? How can I delete theactual  configuration I have already imported in for my actual stakepool account?

**Comment by jrick** [comment]
I was talking about wallet accounts, not stakepool accounts...

I'm unfamiliar with decrediton so i'll let others comment on if it's possible to remove account info for one.

**Comment by lbiazao** [comment]
@jrick I have found the configuration on config.json file and removed. Thank you.

**Comment by lbiazao** [comment]
I have understood the change in validation and needed to create a new pool account to solve the issue. Because i have used the same stakepool script in 2 different wallets  (seeds) and now it's not valid for the wallet anymore.
