### ISSUE TITLE
Option to remove wallet from inside GUI

### ISSUE THREAD

**Issue by jcvernaleo** [decred/decrediton#488]
Someone requested this on slack (so much in scrollback I can't quite find who any more).  This way a user who wants to start over would not need to go through the filesystem.

**Comment by jolan** [comment]
This functionality was removed because it was not properly implemented/wrapped.

I think it should be added back since typically it causes a support incident where the user needs to ask what the path to the wallet is so they can shut down decrediton and remove it.

I think a good implementation would be to present a warning, followed by a 5 second timer that can be cancelled, followed by a status message that reflects whether the wallet was deleted or not.

1) Present a warning to the user.  Something along the lines of "This option lets you permanently delete your wallet and then shuts down Decrediton.  **Your wallet will not be recoverable without the 33 seed words that you were instructed to write down.**"  followed by a big red 'Permanently delete wallet' button.
2) Upon hitting the 'Permanently delete wallet' button, initiate a cancelable countdown timer that presents a status string. "Permanently deleting wallet in 5 seconds..." followed by a 'Cancel' button.   Upon the timer expiring:
  - Inform the user if the wallet was successfully delete or not and then maybe present close/re-open decrediton button or do it automatically after another 5 second countdown.
Upon the cancel button being clicked:
  - Present a 'Permanently delete wallet operation canceleld' message.

Maybe @alexlyp or the designers can chime in with more UI details.  In my opinion, this would be a good task for a new developer.

**Comment by matheusd** [comment]
Latest master has this now.
