### ISSUE TITLE
Audit where tooltips should be added

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#515]

**Comment by linnutee** [comment]
Overview:
- Rescan button?

Receive:
- Address area

Tickets:
- All of the preference icons
- Settings icon
- Information icon
- Revoke icon*
- Import script icon*

**Comment by alexlyp** [comment]
Cool i believe all of those have been added on master.

What do you mean by address area?  which area and what would the tooltip effect be?

**Comment by go1dfish** [comment]
The copy address icon needs a tooltip, and if the copy functionality works on all platforms I'd suggest that the whole address should be clickable to copy to clipboard.

I only know the copy to address button does what it does because I read the code, hadn't tried clicking it before then and I don't see any tooltip for it.

**Comment by Thoughtscript** [comment]
Brief update on the current uses of ReactToolTip as I finish up Issue #567:

1. **components/views/SecurityPage/Page.js** - This is actually an unused ReactToolTip that can be removed completely. I think the intent was to have this here since it's a higher-order component for both views/SecurityPage/Header.js as well as Header/index.js.

2. **components/views/AccountsPage/AccountRow/Row.js** - "Accounts" from main selection sidebar. Used on Accounts that are not default or imported. This needs getContent...
 
3. **components/views/AccountsPage/AccountRow/index.js** - "Accounts" from main selection sidebar. Used on Accounts that are not default or imported.

4. **components/views/ReceivePage/Page.js** - "Receive" from main selection sidebar. Used in account list dropdown.

5. **components/views/TicketsPage/Page.js** - "Tickets" from main selection sidebar. Used after API Key is loaded in.

6. **components/views/SendPage/Page.js** - "Send" from main selection sidebar. Used only on the wallet/account-tip icon/button.
 
7. **components/views/HomePage/Page.js** - "Overview" from main selection sidebar. Used only on the "Rescan Blockchain" button.

8. **components/views/GetStartedPage/DaemonLoading/Form.j**s - Used when you first startu p the app and it's loading the Decred chain. The tip is displayed on the skip sync button that provides an option to skip the sync as a new user.

9. **components/CopyToClipboardButton.js** - Used to show a tooltip on a copy button after something has been copied. The two places where this is used are the components/views/ReceivePage/Page.js and components/SignMessage/index.js.
