### ISSUE TITLE
Update pagination UX

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#732]
Update pagination look and feel to match designer's suggestions.

**Comment by linnutee** [comment]
See [UI components](https://xd.adobe.com/view/82325302-2eb8-4684-9b46-7ef1bc6b227a/ ) and specs: [UI components specs 031017.pdf](https://github.com/decred/decrediton/files/1356155/UI.components.specs.031017.pdf)

Context examples are in "history" as well in the new "my tickets" views:
[decrediton ui v012 - transactions and history - history](https://xd.adobe.com/view/5ca79364-9459-4017-b0b1-7e26f90059fd/)
[decrediton ui v01 - tickets - my tickets](https://xd.adobe.com/view/7707b586-62f0-4c93-afaf-1c5b9432b8eb/screen/5514ce96-bfb4-4eae-b37f-2c87e0d45d1b/My-Tickets)

<img width="717" alt="screen shot 2017-10-04 at 17 36 17" src="https://user-images.githubusercontent.com/17774057/31181665-911c90c8-a92a-11e7-9213-da8c97a5fbf9.png">

-------------------------------------------------
Past releases and references: https://www.notion.so/eeter/Decrediton-UI-knowledge-base-5cc97bc87cc74e80bb4ef42e996fab2d

**Comment by matheusd** [comment]
Preview.
![paginator mp4](https://user-images.githubusercontent.com/1752493/31445457-76df4e18-ae74-11e7-8309-3a452b649a8e.gif)

**Comment by linnutee** [comment]
Interactions look right. Would only recommend adding another hover state for the arrows. Instead of showing the blue backdrop, have the arrows change color. 

E.g. 
```
default: #8997A5 
hover: #0C1E3E 

```

I can't find a good reason why to use a different arrow style for these. Sorry about including those in the first place. Don't mind if they are left as they are, but may be cleaner to just have the same full arrow as used elsewhere.

<img width="772" alt="screen shot 2017-10-12 at 03 06 59" src="https://user-images.githubusercontent.com/17774057/31472964-6de88032-aefa-11e7-885a-58583f160696.png">

**Comment by alexlyp** [comment]
Added in #772
