### ISSUE TITLE
Initial My Tickets mock up

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#735]
First pass can be totally static information while the backend is updated to provide the required ticket status information.

**Comment by linnutee** [comment]
<img width="957" alt="screen shot 2017-10-04 at 18 42 03" src="https://user-images.githubusercontent.com/17774057/31185064-c580369a-a933-11e7-9d2e-cdc4f589329d.png">

[See slides 2-4](https://xd.adobe.com/view/7707b586-62f0-4c93-afaf-1c5b9432b8eb/screen/5514ce96-bfb4-4eae-b37f-2c87e0d45d1b/My-Tickets)
[Tickets views - specs 041017.pdf](https://github.com/decred/decrediton/files/1356428/Tickets.views.-.specs.041017.pdf)

Summary: 
- My tickets view is a sort of combination of History + Voting/Governance views. 
- Each ticket displays a relevant icon depending on its state. 
- Tickets are type of cards that can expanded. 
- When pressed, a ticket expands down in Y and matches size of two tickets. The tickets below should react by moving to a lower position. 
- Second press contracts the ticket.
- Expanded ticket should be able to hold 3 or maximum 4 rows of information. Lets try to keep it as simple as possible...

Possible types of information:
- **Ticket type** displayed as icon + text as hover tooltip
- **Reward DCR** displayed below price as text. Hover on icon shows tooltip that can give an additional info like **reward percentage?** 
- **Date of purchase** displayed next to lock icon.  Hover tooltip can perhaps show the apx. amount of days locked? Also on all types of past tickets, this should show either purchase date + end date or amount of days locked + purchase date on hover? Suggestions welcome. 
- **Transaction tx and status**: confirmations shown in tooltip hover. 
- **Block**
- **Block height**

Context menu is used to filter tickets. The default choice can be **active tickets** that displays all "unmined, immature and live tickets". **Past tickets** should display all voted, expired, missed and revoked tickets. And **Expired**, **Missed** and **Revoked** show only those specific types since they are not common.

Assets:
[decrediton - component icons - 041017.zip](https://github.com/decred/decrediton/files/1356424/decrediton.-.component.icons.-.041017.zip)
[decrediton - ticket icons.zip](https://github.com/decred/decrediton/files/1356421/decrediton.-.ticket.icons.zip)

**Comment by matheusd** [comment]
Preview. Work is currently here: https://github.com/decred/decrediton/compare/master...matheusd:new-tickets-page?expand=1

Notes: Not on a tabbed page because @alexlyp mentioned he was working on #813 and #814, so I'm mocking the MyTickets page as top-level for the moment.

Most of the info is not yet being read from the ticket itself. I'm still figuring out which information *can* be extracted - for example, the design mock shows the ticket price but I'm not yet sure where this information can be found on the ticket info. In fact, I'm pretty sure it can't be found (this is probably related to #683).


![screenshot_2017-10-23_17-24-46](https://user-images.githubusercontent.com/1752493/31909150-e477593c-b817-11e7-9152-83e845148692.png)
![screenshot_2017-10-23_17-24-54](https://user-images.githubusercontent.com/1752493/31909151-e4b7da84-b817-11e7-8222-9f93aae5e880.png)
![screenshot_2017-10-23_17-25-03](https://user-images.githubusercontent.com/1752493/31909152-e4f68cb6-b817-11e7-8b29-64012047a330.png)

**Comment by alexlyp** [comment]
Cool I like it for a first pass.  With the different landing page, how do you go "back" to the initial My Tickets list of categories?

**Comment by matheusd** [comment]
Idea would be to use a back button on top, similar to the transaction details.

**Comment by alexlyp** [comment]
That sounds great
