### ISSUE TITLE
Tooltips don't show after adding stakepool api

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#755]
After successfully adding a stakepool api key no tooltips show up until you click away to another Page then back to the Tickets page.

**Comment by Thoughtscript** [comment]
@alexlyp - now have an answer for this that I'll be checking in shortly. Interestingly, the TicketsPage/Index.js component doesn't go through the normal componentDidMount() method the first time someone passes in an API Key - rebuilding the tooltip in componentDidUpdate() will solve the problem - finishing this up since I had a chance to look at it a little last night and this morning. PR coming soon. Thanks!

**Comment by alexlyp** [comment]
closed
