### ISSUE TITLE
Time since last block 

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#757]
After the recent changes with the i18n implementation, I've noticed some strange counting/ changing on page turn of the time since string at the bottom of the sidebar.

I don't think it was implemented correctly previously so no need to revert.

I'd like to open up discussion about what should be the proper functionality of the "time since block" string here.

We have the new block's timestamp to compare against the current time.  Ideally this would be a component that calculates the number of seconds since the last block then uses a time parser to make it into readable text.  I was never able to figure out a method that could constantly update the component and not have a huge impact on performance

**Comment by matheusd** [comment]
Ok, let me run through the implementation details of that one.

Before the i18n conversion, that label was recalculated every 10 seconds from a dispatched call on the component. That call bubbled all the way up to an action that extracted the last block's timestamp and calculated the relative time (in minutes) until now.

But react-intl has a `<FormattedRelative>` component which is able to automatically translate **and** update relative time strings ("now", "10 seconds ago", "45 seconds ago", "1 minute ago", etc). You just pass it a `Date` object as value (say, date/time of the last block's timestamp) and it will set up triggers and auto update at the "interesting" times at a maximum rate defined by a prop (currently 30 seconds for the block time component in the sidebar).

The problem of it updating when changing pages is (AFAIK) because the sidebar gets umounted/remounted since it is defined on each page. What you see after a page turn is actually the initial value of the component after a remount.

We should recheck this issue after the refactor to a single page container, as that will prevent the sidebar getting remounted all the time and should automatically solve it. If, after that refactor, there are still issues, then we can take another look.

**Comment by alexlyp** [comment]
This was fixed in #772 and i believe it is acting as expected now
