### ISSUE TITLE
Config.json Stakepool data being overwritten

### ISSUE THREAD

**Issue by kandiru** [decred/decrediton#801]
After starting Decredition while having no internet access, I found my config.json file had lost my saved stakepool API key and information.

Trying to replicate it by manually turning off and on my network isn't reproducing the issue, so there is probably some timing involved.

**Comment by matheusd** [comment]
Just had a quick look on the code, if the endpoint that lists available stakepools is not reached (due to a timeout, network error or anything like that) the stakepool information is cleared. The logic for clearing stakepool info should probably be improved.

**Comment by kandiru** [comment]
That would make sense. clear the information for only pools which don't have API key's configured?

**Comment by matheusd** [comment]
That wouldn't work out the way the config is stored. Probably needs to either not do any changes in case of an error or actually handle the specific errors that can happen on the request.

That clearing was added as a fix to an bug that maintained stakepool config after deleting the wallet. What needs to happen is to rework the code to only clear the stakepool config on the the actual condition of wallet having been removed, instead of on *any* error happening.
