### ISSUE TITLE
Add functional Send form

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#81]
For a first pass the send form should include the following things:
- [ ] destination address
- [ ] destination amount
- [ ] account number to use (can just be a text field to start)
- [ ] required confirmations

Once those basics are in:
- [ ] Dropdown list for accounts to use
- [ ] Multiple recipients for Send
- [x] ~~Optional change address~~   This is no longer a requirement of the issue.  discussion is below

We would also like to break out the construct/sign/publish into individual steps so users can confirm transaction before sign/publish.

**Comment by behindtext** [comment]
I recommend not exposing the optional change address to users since change is supposed to flow to a given account's addresses from branch 1 (using BIP0032 notation, m/i/1).  If the change address can be manually set by a user, it could lead to bad UX.  If it is possible to have the change address automatically set by dcrwallet, that would be ideal.

**Comment by alexlyp** [comment]
@behindtext noted.  agree with that assessment

**Comment by jcvernaleo** [comment]
In particular, for a somewhat new user, the whole change address option leads for way more way to go wrong than right.

**Comment by jrick** [comment]
the optional "change" address is exposed by the RPC in order to make it possible to construct sweep transactions (by setting a change address without any other addresses: all possible output value is sent to the change address).  It should not be exposed in the UI as a change address, but can be used if you add a new view to construct sweep transactions.
