### ISSUE TITLE
refactor internationalization

### ISSUE THREAD

**Issue by Jascha-Sundaresan** [decred/decrediton#811]
right now we have a ton of redundancy

there are at least 3 different tooltips w/ the same message "Accounts" but each with a different verbose key.

If we keep our translations in a single tree object, we can flatten that and pass it into IntlProvider at the top of our app and then we only need to use the `id` property in `T` when setting messages.

This also has the added bonus of a centralized location for all our internationalizations that is necessarily always in sync and possibly even obviates the need for react-intl-po

**Comment by matheusd** [comment]
During initial intl work, we discussed removing all copy from the components and leaving only the id for translation but we decided not to do it (leaving the actual default english string in the individual templates).

The identical messages throughout the app use different IDs because they are present in different contexts and so may be translated differently on different languages. This was also discussed with the current internationalization team (@peter_zen and @emiliomann on slack). Transifex makes it easy to translate repeated messages anyway.

The specific case of the "Accounts" tooltip is because we didn't have a unified component for the account icon (instead of having a single `<AccountsLink />` or something, we have three `<a data-tip=...>`). One of my latest PRs unified the various selects into a single AccountsSelect, so I think (though I haven't checked) that should have reduced the number of repeated tips.

With the new tooltip you've built that can use `<T` as content, the places using `defineMessages()` should be even more reduced (basically just the input placeholders and a few internal messages  that probably should be refactored in the snackbar issue anyway).

After all that is done, centralizing the remaining messages should be easy.

**Comment by Jascha-Sundaresan** [comment]
The catch with including more than just `id` is that we can't set messages programmatically. 

eg:
```
message = "transation.type." + type;
<T id={ message } />
```

**Comment by matheusd** [comment]
That's certainly an advantage os using id's only, sure.

**Comment by go1dfish** [comment]
The thinking here was the esp for people new to the codebase, searching for text in the UI is often one of the quickest ways to find what you are after.

I don't recall anyone being strongly in favor of one way over another but that was the argument for the approach taken.

Being able to deduplicate common messages would be good though.  Perhaps it is possible to adopt a hybrid approach?

**Comment by matheusd** [comment]
For deduplication all you need is to define the `<T ...` object (of the common message) in a common file, and import it everywhere it is used.

I think I used that approach in a couple of places, but that is a tricky thing to do, because the context of the string changes and in languages other than english we may need a different translation.

Concrete example: On the "my tickets" page, the initial overview lists the amount of tickets for each type (so there's a translation for "Voted", "Revoked", "Missed", etc). Initially I used the same message as ticket type displayed in other places, because that doesn't make a difference in english. But in portuguese, I need to display that initial overview in a plural form ("Votados", "Revogados", "Perdidos", etc) so I **can't** use the same message as the one used for a single ticket. Therefore, I need a different message for the overview page.

Naively reading the code in english you'd think the occurrences of the same translated "voted" string in multiple places is a duplicated message and should be collapsed into a single message, shared among components. But they are actually needed, because in portuguese the context where these messages appear is different and they have different translations.

So, I've written all that to say that I'm not against combining duplicated messages (I've done it myself in a few places), but people doing it should make sure that no context is lost that is needed in other languages.

**Comment by vctt94** [comment]
Is this still an issue?
