### ISSUE TITLE
Allow for seed hex input as well

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#847]
There should be an option for a user to enter in the hex of the seed instead of the full 33 word seed.

**Comment by brunobraga95** [comment]
since this is one of the first issues I am trying to work on, I have a few questions that I believe may help other possible new contributors.

- why do we need a hex version of the seed (because it's shorter? for a matter of convenience?)
- where can I get this hex version, when I first compiled the project I was given a seed that is pretty much 33 english words
- what are the places where the hex input version should be implemented? just the initial screen when we first create our wallet? does that mean that besides the 33 words that we receive, we should also receive the hex version?

**Comment by matheusd** [comment]
1. As an alternative way of inputting the seed. The seed is actually a 256 bit number that can be displayed/entered in several different fashions. The pgp word list (what we usually call "the seed") is just one way of encoding the underlying HD seed. The hex seed is another.

2. AFAIK only command line dcrwallet displays the hex seed when creating the wallet. Maybe we could modify decrediton to also display the hex seed.

3. Only initial import screen. It is an alternative input mode, so user may enter either the 33 word seed **or** the hex seed.

**Comment by brunobraga95** [comment]
cool, I will work on this issue.
