### ISSUE TITLE
List of wallet statistics for Statistics page

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#901]
Here is a brief list of statistics we'd like to include on the first pass of the Statistics page.  Each of these statistics should be able to be graphed over a period of time (week, month, year, custom).

- Total ROI (in DCR and %) of staking. 
- Total wallet balance (across all accounts or subset of accounts)
- Avg time to vote (show histogram to reinforce Gaussian distribution of ticket selection)
- Tx/Ticket/Pool fees paid

Feel free to add anymore below but these should at least get us started.

**Comment by matheusd** [comment]
- Number of vote choices for the agendas (to check whether the pool is honoring the selected choice).

Also, we should consider whether the statistics will be calculated in decrediton or on dcrwallet, and if they will be calculated on every run or cached.

I'm mentioning this because #815 proposes switching to fully streamed `getTickets()` instead of downloading all at once, so if that gets implemented, the way to calculate the statistics may change.

**Comment by alexlyp** [comment]
I think they should be calculated in decrediton and done on every request based on date range.  The overhead should be pretty low since even on a very heavily used wallet over a large range we should only be dealing with thousands of data points to analyze which should cause no noticeable slow down.  

Now caching past transactions that were fetched is a good idea so we don't have to constant ask dcrwallet about transactions that we already know about.

**Comment by AlanBarber** [comment]
Sort of a tangent but I know I would love to see a tool for exporting to CSV transactions and ticket data. It would be useful for quicking dumping data so people can run their own stats in 3rd party tools as well as for financial reporting like with taxes.

**Comment by alexlyp** [comment]
Yup, https://github.com/decred/decrediton/issues/912

**Comment by vctt94** [comment]
Now we have Statitics pages and export transactions option.
