### ISSUE TITLE
Add loading/progress for all actions while processing

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#918]
There are a few instances where there is no feedback while a wallet request is in flight.  

After a brief audit of current actions here is a list of known places where we should add a loading or some other feedback to the user so they know something is occurring:

- ChangePassphrase
- ImportScript
- Start/StopTicketBuyer
- UpdateTicketBuyerConfig

The Ticket buyer ones aren't super important since those will be mostly going away with the upcoming staking account implementation.

**Comment by brunobraga95** [comment]
is there a specific loading indicator already built that we are supposed to use, or is this one going to be build from scratch? I believe that for this type of loading process a good component would be something that would make the whole screen darker (overlay) with a loading animation fixed in the center.
what are your thoughts on this?

**Comment by matheusd** [comment]
For the moment, I think the simplest solution is to pass a `loading` prop which will add the simple loading indicator in the buttons. See the send transaction page for an example.

**Comment by alexlyp** [comment]
Right, I think that's the best approach for now.
