### ISSUE TITLE
Double attempt of importing script

### ISSUE THREAD

**Issue by matheusd** [decred/decrediton#965]
If you import a script and immediately purchase a ticket afterwards (either during the rescan or after it). it tries to import the script again.

**Comment by alexlyp** [comment]
So this is partially an old remnant, but on every purchase ticket attempt we also submit an import script request prior to issuing the purchase ticket request to the wallet to ensure that the script being used for the multisig stakepool address is redeemable by this wallet.  

We've added this check and protection when adding api-keys, but I still think we need to keep it because there may be some users with older wallets that have invalid api-keys in their settings.

**Comment by alexlyp** [comment]
It's a bit overkill and but I'd rather be sure to avoid wedged tickets for the user.

I do think we need to fix or consume the success messages here.  Eg we should not show "You successfully imported script" when purchasing ticket.
