### ISSUE TITLE
User reporting voting only wallet not showing tickets on the My Tickets Page

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#997]
User has the following set up:
- Voting-only wallet
- No stakepool configured

Balances shown to the users appear to be correct under account details and when the user was able to submit a `dcrctl --wallet getstakeinfo` request the numbers were accurate.  It appears that the problem lies with the GetTickets request in dcrwallet or the decision making of ticket organization in decrediton.

**Comment by alexlyp** [comment]
After rescan numbers on ticket page are correct

**Comment by matheusd** [comment]
Was trying to replicate this one by importing a voting wallet, and made a mistake that may have been the origin of this:

On seed input, instead of selecting "import seed", I pressed "next" after being shown a seed for a new wallet, then imported my existing seed. No transactions or tickets were shown. After rescan, the transactions and tickets were correctly shown.

I believe there's a check that when a new wallet is created using a new seed the rescan is not performed (as it is assumed no transactions exist for a brand new wallet). I'll perform a few more simulations, but if that is the problem then it's an easy fix.

**Comment by matheusd** [comment]
Ok, just confirming this is what I saw:
- Going through the "existing seed" page issued a rescan and showed the transactions
- Going through the "create seed" page did **not** issue the rescan and did **not** show the transactions.

@alexlyp If you can confirm whether the user saw the screen to discover accounts (probably not, ss below) and if a rescan wasn't issued right after creation, then this is probably the root cause of this problem. The tickets not showing is similar to #993 (tickets only listed on startup).

![screenshot_2017-12-18_13-10-52](https://user-images.githubusercontent.com/1752493/34113039-93dc2c0a-e3f5-11e7-90b3-6e3f89722c08.png)
